### ISSUE TITLE
全国主要都市来訪者・訪問者推移指数オープンデータへの切り替え

### ISSUE THREAD

**Issue by uribo** [tokyor/jpcovid19#1]
ヤフー・データソリューションが`全国主要都市来訪者・訪問者推移指数オープンデータ(47都道府県と県庁所在市、政令指定都市の来訪者と往訪者の日次前年比) `を2020年4月20日より公開。

https://ds.yahoo.co.jp/topics/202004202.html

これに伴い、「東京23区の滞在人口推計値の日次推移データ（全体・来訪者・住人）」は統合され、更新されないとのこと。

`read_yds_tky23()`はそのまま残しておいてもよいが、新しいデータに対応した関数を用意する。

**Comment by yutannihilation** [comment]
なんと！
